# Site settings
title: My Tech Blog
description: Sharing thoughts on tech topics
baseurl: "" # Set this to your base URL if your site is hosted in a subdirectory

# Default language
default_lang: de

# Localization
locales:
  - de
  - en

# URL structure
permalink: "/:lang/:title/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation
navigation:
  - title: Home
    url_de: /
    url_en: /en/
  - title: About
    url_de: /about/
    url_en: /en/about/
  # Add more navigation links as needed

# Gems
plugins:
  - jekyll-feed

# Jekyll i18n
jekyll_i18n:
  locales:
    - de
    - en

# Jekyll-assets
assets:
  skip_baseurl_with_assets: false

# Jekyll-feed
feed:
  title: My Tech Blog Feed
  description: The latest posts from My Tech Blog
  author:
    name: Your Name
  lang: en

# Development settings
markdown: kramdown
theme: minima